project/app/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from app.views import (
    CustomLoginView,
    create_report,
    daily_reports,
    delete_report,
    edit_report,
    get_manager_page,
    main_page,
    monthly_detail,
    monthly_reports,
)

app_name = 'app'

urlpatterns = [
    path('', main_page, name='main_page'),
    path('daily/<slug:date>/', daily_reports, name='daily_reports'),
    path('monthly/', monthly_reports, name='monthly_reports'),
    path('monthly/<slug:month>/', monthly_detail, name='monthly_detail'),
    path('managers/<int:pk>/', get_manager_page, name='personal'),
    path('report/', create_report, name='report'),
    path('report/<int:pk>/edit/', edit_report, name='edit_report'),
    path('report/<int:pk>/delete/', delete_report, name='delete_report'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

project/core/urls.py
from django.contrib import admin
from django.urls import include, path

handler404 = 'app.views.page_not_found'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'), name='app'),
]

project/app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Role(models.Model):
    name = models.CharField(
        max_length=255
    )
    slug = models.CharField(
        max_length=255,
    )

    class Meta:
        verbose_name = 'Роль'
        verbose_name_plural = 'Роли'

    def __str__(self):
        return self.name


class User(AbstractUser):
    middle_name = models.CharField(
        verbose_name='Отчество',
        max_length=255,
        blank=True
    )
    role = models.ForeignKey(
        Role,
        on_delete=models.SET_NULL,
        related_name='users',
        blank=True,
        null=True
    )

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Report(models.Model):
    manager = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='reports'
    )
    address = models.CharField(
        verbose_name='Адрес',
        max_length=255,
    )
    date = models.DateField(
        verbose_name='Дата'
    )
    income = models.DecimalField(
        verbose_name='Выручка',
        max_digits=7,
        decimal_places=2
    )

    class Meta:
        verbose_name = 'Отчёт'
        verbose_name_plural = 'Отчёты'

    def __str__(self):
        return str(self.date)

project/app/forms.py
from django import forms


class ReportForm(forms.Form):
    date = forms.DateField(
        widget=forms.SelectDateWidget(attrs={'class': 'form_date'})
    )
    address = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form_address'})
    )
    income = forms.DecimalField(
        widget=forms.NumberInput(attrs={'class': 'form_income'})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].label = 'Дата'
        self.fields['address'].label = 'Адрес'
        self.fields['income'].label = 'Выручка'

project/app/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.db.models import CharField, DecimalField, F, Sum, Value
from django.db.models.functions import Cast, Concat, ExtractMonth, ExtractYear
from django.shortcuts import redirect, render
from django.urls import reverse

from app.forms import ReportForm
from app.models import Report, User

# Страницы для админа


@login_required
def main_page(request):
    """Главная страница."""

    if request.user.role.slug == 'admin':
        managers = User.objects.filter(role__slug='manager')
        return render(request, 'main_page.html', {'managers': managers})

    return redirect(reverse('app:personal', kwargs={'pk': request.user.pk}))


@login_required
def daily_reports(request, date):
    """Страницы ежедневных отчётов."""

    if request.user.role.slug == 'admin':
        dates = [
            str(date[0]) for date
            in Report.objects.values_list('date').order_by('-date').distinct()
        ]
        reports = Report.objects.filter(date=date)
        context = {'reports': reports, 'dates': dates, 'current_date': date}
        return render(request, 'daily_reports.html', context)

    return render(request, '404.html')


@login_required
def monthly_reports(request):
    """Общая страница сводных отчётов."""

    if request.user.role.slug == 'admin':
        month_income = (
            Report.objects
            .annotate(month=ExtractMonth('date'))
            .values('month')
            .annotate(year=ExtractYear('date'))
            .annotate(total=Cast(Sum('income'), output_field=DecimalField()))
            .annotate(
                detail=(
                    Concat(
                        F('month'),
                        Value('-'),
                        F('year'),
                        output_field=CharField()
                    )
                )
            )
        )
        return render(
            request, 'monthly_reports.html', {'month_income': month_income}
        )

    return render(request, '404.html', {'users': request.user})


@login_required
def monthly_detail(request, month):
    """Страница детализации отчётности за выбранный месяц."""

    if request.user.role.slug == 'admin':
        month_year = month.split('-')
        reports = (
            Report.objects.filter(
                date__year=month_year[1],
                date__month=month_year[0]
            )
        )
        return render(request, 'monthly_detail.html', {'reports': reports})

    return render(request, '404.html', {'users': request.user})


# Страницы для менеджера


@login_required
def get_manager_page(request, pk):
    """Персональная страница менеджера."""

    if (
        request.user.pk == pk
        or request.user.role.slug == 'admin'
        and pk != 1
    ):
        if request.user.pk == pk and request.user.role.slug == 'admin':
            return redirect(reverse('app:main_page'))

        reports = Report.objects.filter(manager=pk).order_by('-date')
        manager = User.objects.get(pk=pk)
        context = {
            'reports': reports,
            'manager': manager
        }
        return render(request, 'personal.html', context)

    return render(request, '404.html', {'users': request.user})


@login_required
def create_report(request):
    """Страница добавления отчёта."""

    if request.user.role.slug == 'admin':
        return redirect(reverse('app:main_page'))

    if request.method == 'POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            manager = request.user
            address = form.cleaned_data['address']
            date = form.cleaned_data['date']
            income = form.cleaned_data['income']
            Report.objects.get_or_create(
                manager=manager,
                address=address,
                date=date,
                income=income
            )
            return redirect(
                reverse('app:personal', kwargs={'pk': request.user.pk})
            )
    else:
        form = ReportForm(initial={'date': datetime.now()})
    return render(request, 'report.html', {'form': form})


@login_required
def edit_report(request, pk):
    """Страница редактирования отчёта."""

    report = Report.objects.get(pk=pk)

    if request.method == 'POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            report.address = form.cleaned_data['address']
            report.date = form.cleaned_data['date']
            report.income = form.cleaned_data['income']
            report.save()
            return redirect(
                reverse('app:personal', kwargs={'pk': request.user.pk})
            )
    else:
        data = {
            'address': report.address,
            'date': report.date,
            'income': report.income
        }
        form = ReportForm(initial=data)
    return render(request, 'report.html', {'form': form})


@login_required
def delete_report(request, pk):
    report = Report.objects.get(pk=pk)
    report.delete()
    return redirect(reverse('app:personal', kwargs={'pk': request.user.pk}))


class CustomLoginView(LoginView):
    """Авторизация."""

    def form_invalid(self, form):
        response = super().form_invalid(form)
        messages.error(
            self.request,
            'Неправильно введён логин и/или пароль, \
                или такого пользователя не существует.'
        )
        return response


def page_not_found(request, exception):
    return render(request, '404.html', {'path': request.path}, status=404)

project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">
        <title>{% block title %}Тестовый сайт{% endblock %}</title>
        </head>
    <body>
        {% if user.is_authenticated %}
                <div id="sidebar" class="menu">
                    <nav>
                        {% block sidebar %}
                            <a href="{% url 'app:main_page' %}" class="{% if request.resolver_match.view_name == 'app:main_page' %}active_page{% endif %}">Главная</a>
                            {% if request.user.role.slug == 'admin' %}
                                <a href="{% url 'app:daily_reports' date=newest_date %}" class="{% if request.resolver_match.view_name == 'app:daily_reports' %}{% if request.resolver_match.kwargs.date == newest_date %}active_page{% endif %}{% endif %}">Ежедневные отчёты</a>
                                <a href="{% url 'app:monthly_reports' %}" class="{% if request.resolver_match.view_name == 'app:monthly_reports' %}active_page{% endif %}">Сводные отчёты</a>
                            {% endif %}
                            {% if manager.pk == request.user.pk and manager.reports.count < 10 %}
                                <a href="{% url 'app:report' %}" >Добавить отчёт</a>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <form method="post" action="{% url 'app:logout' %}" style="float: right">
                                    {% csrf_token %}
                                    <button type="submit" class='logout'>Выйти</button>
                                </form>
                            {% endif %}
                        {% endblock %}
                    </nav>
                </div>
        {% endif %}
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

project/templates/daily_reports.html
{% extends "base.html" %}
{% block content %}
    <h1>Отчёт за {{ request.resolver_match.kwargs.date }}</h1>
    <table border="0" class="daily">
        <thead>
            <tr>
                <th>Менеджер</th>
                <th>Адрес</th>
                <th>Выручка</th>
            </tr>
        </thead>
        <tbody>
            {% for report in reports %}
                <tr>
                    <td>{{ report.manager.last_name }} {{ report.manager.first_name }} {{ report.manager.middle_name }}</td>
                    <td>{{ report.address }}</td>
                    <td>{{ report.income }} &#8381;</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="daily_buttons">
        {% for date in dates %}
            <a href="{% url "app:daily_reports" date=date %}" class="{% if request.resolver_match.view_name == 'app:daily_reports' %}{% if request.resolver_match.kwargs.date == date %}active{% endif %}{% endif %}">{{ date }}</a>
        {% endfor %}
    </div>
{% endblock content %}

project/templates/main_page.html
{% extends "base.html" %}
{% block content %}
    <h1>Страница пользователя "{{ request.user.role }}"</h1>
    <h2>Список менеджеров</h2>
    <table>
        <thead>
            <tr>
                <th>ФИО</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for manager in managers %}
                <tr>
                    <td>{{ manager.last_name }} {{ manager.first_name }} {{ manager.middle_name }}</td>
                    <td><a href="{% url "app:personal" pk=manager.pk %}" class="personal_page">страница</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

project/templates/monthly_detail.html
{% extends "base.html" %}
{% block content %}
    <h1>Пользователи</h1>
    <table border="1">
        <thead>
            <tr>
                <th>Менеджер</th>
                <th>Дата</th>
                <th>Выручка</th>
            </tr>
        </thead>
        <tbody>
            {% for report in reports %}
                <tr>
                    <td>{{ report.manager.last_name }} {{ report.manager.first_name }} {{ report.manager.middle_name }}</td>
                    <td>{{ report.date }}</td>
                    <td>{{ report.income }} &#8381;</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

project/templates/monthly_reports.html
{% extends "base.html" %}
{% block content %}
    <h1>Сводные отчёты по месяцам</h1>
    <table border="0">
        <thead>
            <tr>
                <th>Месяц</th>
                <th>Общая сумма</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for income in month_income %}
                <tr>
                    <td>{{ income.month }}-{{ income.year }}</td>
                    <td>{{ income.total }},00 &#8381;</td>
                    <td><a href="{% url "app:monthly_detail" month=income.detail %}" class="personal_page">детализация</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

project/templates/personal.html
{% extends "base.html" %}

{% block content %}
<h1>Отчёты пользователя {{ manager.last_name }} {{ manager.first_name }} {{ manager.middle_name }}</h1>
    {% if manager.reports.count >= 10 %}
        <div class="alert alert-error" style="border: none;">
            Превышено допустимое кол-во добавленных отчётов.
            <br>
            Для добавления новых нужно удалить старые.
        </div>
    {% endif %}
    <table border="1">
        <thead>
            <tr>
                <th>Адрес</th>
                <th>Дата</th>
                <th>Выручка</th>
                {% if request.user.role.slug == 'manager' %}
                <th></th>
                <th></th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for report in reports %}
                <tr>
                    <td>{{ report.address }}</td>
                    <td>{{ report.date }}</td>
                    <td>{{ report.income }} &#8381;</td>
                    {% if request.user.role.slug == 'manager' %}
                    <td>
                        {% if manager.pk == request.user.pk and report.date.month == current_month %}
                            <a href="{% url 'app:edit_report' pk=report.pk %}" class="personal_page">Редактировать</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if manager.pk == request.user.pk %}
                            <a href="{% url 'app:delete_report' pk=report.pk %}" class="personal_page">Удалить</a>
                        {% endif %}
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

project/templates/report.html
{% extends "base.html" %}

{% block content %}
    <h1>Отчёт пользователя {{ request.user.last_name }} {{ request.user.first_name }} {{ request.user.middle_name }}</h1>
    <form method="post" class="my-form">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-field">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="submit-button">Сохранить</button>
    </form>
    
{% endblock content %}